INTERFACE
SUBROUTINE ESETUP_TRANS(KMSMAX,KSMAX,KDGL,KDGUX,KLOEN,LDSPLIT,KTMAX,KRESOL,&
 & PEXWN,PEYWN,KNOEXTZL,KNOEXTZG,PWEIGHT,LDGRIDONLY,LDUSEFFTW)
  USE PARKIND1  ,ONLY : JPIM     ,JPRB

  IMPLICIT NONE

  INTEGER(KIND=JPIM),INTENT(IN)    :: KMSMAX
  INTEGER(KIND=JPIM),INTENT(IN)    :: KSMAX
  INTEGER(KIND=JPIM),INTENT(IN)    :: KDGL
  INTEGER(KIND=JPIM),INTENT(IN)    :: KDGUX
  INTEGER(KIND=JPIM),INTENT(IN)    :: KLOEN(:)
  LOGICAL           ,OPTIONAL,INTENT(IN)    :: LDSPLIT
  INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KTMAX
  INTEGER(KIND=JPIM),OPTIONAL,INTENT(INOUT) :: KRESOL
  REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)    :: PEXWN
  REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)    :: PEYWN
  REAL(KIND=JPRB)   ,OPTIONAL,INTENT(IN)    :: PWEIGHT(:)
  INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KNOEXTZL
  INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN)    :: KNOEXTZG
  LOGICAL           ,OPTIONAL,INTENT(IN)    :: LDGRIDONLY
  LOGICAL           ,OPTIONAL,INTENT(IN)    :: LDUSEFFTW
END SUBROUTINE ESETUP_TRANS
END INTERFACE
